// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package destination

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"aws.accessKeyId": {
			Default:     "",
			Description: "amazon access key id",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"aws.region": {
			Default:     "",
			Description: "aws.region is the region where the stream is hosted",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"aws.secretAccessKey": {
			Default:     "",
			Description: "amazon secret access key",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"stream_arn": {
			Default:     "",
			Description: "stream_arn is the Kinesis stream's Amazon Resource Name",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"stream_name": {
			Default:     "",
			Description: "stream_name is the name of the Kinesis Data Stream",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"use_single_shard": {
			Default:     "true",
			Description: "use_single_shard is a boolean that determines whether to add records in batches using KinesisClient.PutRecords (ordering not guaranteed, records written to multiple shards) or to add records to a single shard using KinesisClient.PutRecord (preserves ordering, records written to a single shard) Defaults to false to take advantage of batching performance",
			Type:        sdk.ParameterTypeBool,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
